"""empty message

Revision ID: 323991cccb3f
Revises: 
Create Date: 2020-04-22 13:19:53.552531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323991cccb3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_group',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_group')
    # ### end Alembic commands ###
